apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mern-backend
  template:
    metadata:
      labels:
        app: mern-backend
    spec:
      containers:
        - name: backend
          image: 548112056811.dkr.ecr.us-west-1.amazonaws.com/mern-backend:latest
          env:
            - name: MONGODB_URI
              value: "mongodb+srv://yogi:Mischief1999@mern-auth.qjt4f38.mongodb.net/?retryWrites=true&w=majority&appName=mern-auth"
            - name: JWT_SECRET
              value: "112899f447ae827162152318f0b40b37f3dccd7cf5769aa1b8fbbcef61aeb601"
            - name: NODE_ENV
              value: "production"
          ports:
            - containerPort: 80
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mern-backend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: mern-backend
