apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
      color: green
  template:
    metadata:
      labels:
        app: backend
        color: green
    spec:
      containers:
      - name: backend
        image: 548112056811.dkr.ecr.us-west-1.amazonaws.com/mern-backend:latest
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: ecr-secret
      # If needed, uncomment this to use an ECR pull secret:
      # imagePullSecrets:
      # - name: ecr-secret
