apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  selector:
    app: frontend
    color: blue  # Change to green when switching
  ports:
    - port: 80
      targetPort: 3000
