apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
      color: green
  template:
    metadata:
      labels:
        app: frontend
        color: green
    spec:
      containers:
      - name: frontend
        image: 548112056811.dkr.ecr.us-west-1.amazonaws.com/mern-frontend:latest
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: ecr-secret  # <-- Add this to use the secret for pulling the image
