apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
      color: blue
  template:
    metadata:
      labels:
        app: frontend
        color: blue
    spec:
      containers:
      - name: frontend
        image: 548112056811.dkr.ecr.us-west-1.amazonaws.com/mern-frontend:latest
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: ecr-secret
      # If using private ECR and your cluster needs auth:
      # imagePullSecrets:
      # - name: ecr-secret
