apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer
  selector:
    app: backend
    color: blue  # Change to green when switching
  ports:
    - port: 80
      targetPort: 5000
