apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend
spec:
  selector:
    app: frontend
    version: {{ .Values.version | default "blue" }}
  ports:
    - port: 80
      targetPort: 3000
